ingredient = {"huile de Tournesol": 598,
              "Vinaigre balsamique": 534,
              "Vinaigre de cidre": 1028,
              "vin blanc de cuisine bio": 377,
              "Vinaigre d'alcool bio": 499,
              "Soude en Cristaud": 518,
              "Huile d'olive": 449,
              "Papier cuisson": 5,
              "Aluminium": 25,
              "Poivre Gris": 138,
              "Miel de fleurs liquide": 143,
              "Semoule": 351,
              "Riz Long": 84,
              "Cornflakes": 666,
              "Amandes Effilees": 45,
              "thé Vert": 15,
              "Pâtes à tartiner": 2,
              "Sucre en Morceau": 522,
              "Pâtes Torti": 540,
              "Persil haché": 191,
              "sel": 127,
              "Bonbon Celebration": 10,
              "Melange Raisins - Noisettes - amandes - Baie de Goji": 200,
              "Cognac": 15,
              "Nutergia produit pour mieux digérer": 266,
              "Sucre glace": 500,
              "Sucre en Poudre": 203,
              "Vermicelles": 254,
              "Poivre Noir": 256,
              "Olive Tramier": 160,
              "Miel de fleurs crémeux solide": 974,
              "Lune de Miel": 488,
              "Bouillon de Volaille": 15,
              "Feuille de Laurier": 23,
              "Feuille de thym": 52,
              "Huile essentiel Bio": 36,
              "Whisky": 342,
              "Rhum": 322,
              "Feuille de Framboisier": 11,
              "Levure Chimique": 5,
              "Farine": 848,
              "Purée de Piment espelette": 190,
              "Nescafé special filtre café": 25,
              "Confiture de mure et Framboises": 120,
              "Ciboulette haché": 93,
              "Muscade Moulue": 123,
              "ail": 1,
              "chocolat au lait": 520,
              "Pain de Mie": 11,
              "Nutella": 1,
              "Pruneau d'agen": 255,
              "Pruneau d'agen dénoyautés": 370,
              "Taylors Rose Lemonade": 1,
              "Taylors Lychee & Lime": 1,
              "Taylors Mandarin & ginger": 4,
              "Taylors Sour cherry": 1,
              "Taylors Mango & Cardamom": 3,
              "Taylors Strawberry & Vanilla": 5,
              "Taylors White hibiscus & peach": 5,
              "Nescafé Cappuccino cremig zart": 2,
              "Nescafé 3 en 1": 2,
              "Nescafé espresso": 6,
              "Café roma": 1,
              "sucre en poudre flute": 4,
              "sel Burger King": 1,
              "Speculoos": 2,
              "Thon entier au naturel": 5,
              "Thon blanc au naturel": 1,
              "Thon entier Huile de Tournesol": 1,
              "Thon entier Huile d'olive": 1,
              "Thon vinaigre le Mariné": 2,
              "Sardine Parmentier": 2,
              "Filets de Maquereaux": 1,
              "Filets de Maquereaux Poivrons et thym": 1,
              "Filets de Maquereaux Arrabbiata": 1,
              "Sardine Parmentier Citron et Thym": 1,
              "Tartinade au saumon": 1,
              "Jus de pomme": 1,
              "Coca": 2,
              "Cornichons": 360,
              "Coeur de sucrine": 1,
              "café bio": 178,
              "Vinaigrette Moutarde": 810,
              "comté": 40,
              "Gorgonzola": 98,
              "emmental": 308,
              "Moutarde": 2,
              "Beurre": 104,
              "fois Gras": 1,
              "Oeufs": 2,
              "Lait": 250,
              "Banane": 2,
              "Levure de Boulanger": 42,
              "baguette": 1,
              "concombre": 0,
              "Petit suisse": 5,
              "blanc de dinde": 0,
              "crême liquide": 40,
              "Bouquet estragon": 15,
              }

